spring:
  cloud:
    gateway:
      routes:
        - id: calculatrice-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/calcul/**
        - id: statistique-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/stats/**