spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: calculatrice-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/calcul/**
        - id: calculstatistique-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/stats/**

server:
  port: 8181